name: 'Generate Space from openapi.yaml'
description: 'Generate a GitBook space based on your OpenAPI spec'
inputs:
  file:
    description: 'The path to your openapi.yaml in your repository'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - run: "npx @gitbook/openapi -f ${{inputs.file}}"
      shell: bash
    - run: "git add . && git commit -m \"Update docs from ${{inputs.file}}\" && git push"
      shell: bash

