name: 'Generate Space from openapi.yaml'
description: 'Generate a GitBook space based on your OpenAPI spec'
inputs:
  file:
    description: 'The path to your openapi.yaml in your repository'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - run: "npx @gitbook/openapi -f ${{inputs.file}}"
      shell: bash
    - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff
          git diff-index HEAD
          git diff-index --quiet HEAD || git commit -am "docs(openapi): update docs for ${{inputs.file}}"
      shell: bash
    - run: "git push origin $(git branch --show-current) || true"
      shell: bash

